### ISSUE TITLE
Action tracking

### ISSUE THREAD

**Issue by r12a** [w3c/modern-tooling#50]
It's not clear to me, looking at the doc, what we will use to replace the actions part of Tracker, which we in i18n, and i guess others, use quite heavily.

I have a request: whatever action tracker we end up using would be a little more useful if we could assign actions to more than one person at a time. For example, when using Tracker, we often want assign everyone in the i18n WG to take a look at a document prior to the next meeting, but we are currently unable to do that.  There are some particular aspects of this worth teasing out: 
(1) it should be possible to establish pre-set groups (such as everyone in the WG, or everyone in the XYZ task force), or to create adhoc groups of people
(2) everyone assigned should be notified by email/twitter or whatever their preferred notification method is
(3) it should be possible, when listing the actions, to see who is assigned without swamping the UI with lists of names
(4) it would be handy to be able to close the action item for some people but not for others (eg. remove names of those who already reviewed the document, leave on those who haven't yet) - ie. it should be possible to easily edit the list of actionees.

**Comment by marcoscaceres** [comment]
> (1) it should be possible to establish pre-set groups (such as everyone in the WG, or everyone in the XYZ task force), or to create adhoc groups of people

It's possible to set such groups up on GH. E.g., "editors", "contributors", "reviewers", etc. However, I'm not sure if they can then be targeted for actions as a group.  

> (2) everyone assigned should be notified by email/twitter or whatever their preferred notification method is

People can subscribe (i.e., pull) from things they are interested in in the ways they want already. E.g., some people prefer email, others prefer just coming to GH... while others prefer neither. It depends on the community and should be left to the community, IMO. What matters is that people have the ability to create their own tooling for this through APIs available through, for instance, GH.  

> (3) it should be possible, when listing the actions, to see who is assigned without swamping the UI with lists of names

I think in practice this rarely makes sense. Assigning a group of people to do something will still result in only ~5% of them doing any work (i.e., group behavior is governed by power law distributions, specially in open source projects - and in particular in standardization). 

> (4) it would be handy to be able to close the action item for some people but not for others (eg. remove names of those who already reviewed the document, leave on those who haven't yet) - ie. it should be possible to easily edit the list of actionees.

GitHub supports lists, like this:
- [x] do foo - Mike
- [ ] do bar - John 
- [ ] do baz - Wendy

They could be re-purposed as above for actions.
