### ISSUE TITLE
CR support

### ISSUE THREAD

**Issue by plehegar** [w3c/modern-tooling#74]
Tracked at https://github.com/w3c/echidna/issues/522

**Comment by plehegar** [comment]
- [x] Support in Echidna https://github.com/w3c/echidna/issues/522
- [ ] new entries in https://github.com/w3c/transitions are notified to Chairs (see https://github.com/w3c/transition-issues-bot)
- [ ] transition requirements updated. See https://github.com/w3c/transitions/issues/63
- [ ] announced to chairs and spec-prod

**Comment by plehegar** [comment]
THis is also linked to #72

**Comment by plehegar** [comment]
Updated milestones calculator to support echidna.

**Comment by tripu** [comment]
(Title should be &ldquo;CR support&rdquo;, because support in Echidna is already done, and that's just one part.)
